### ISSUE TITLE
Query input with option looses validation information

### ISSUE THREAD

**Issue by perok** [softwaremill/tapir#237]
At the moment I have this setup for Enumeratum:

``` scala
  implicit def validatorEnumeratumString[T <: enumeratum.EnumEntry](
      implicit enum: enumeratum.Enum[T]): Validator[T] =
    Validator.enum(enum.values.toList)

  implicit def schemaForEnumeratumString[T <: enumeratum.EnumEntry]: SchemaFor[T] =
    SchemaFor(Schema.SString)

  implicit def plainCodecEnumeratumString[T <: enumeratum.EnumEntry](
      implicit enum: enumeratum.Enum[T]): Codec.PlainCodec[T] =
    Codec.stringPlainCodecUtf8
      .mapDecode(s =>
        enum.withNameInsensitiveOption(s) match {
          case Some(a) => DecodeResult.Value(a)
          case None =>
            DecodeResult.Mismatch(s"One of: ${enum.values.map(_.entryName).mkString(", ")}", s)
      })(_.entryName)
      .validate(validatorEnumeratumString(enum))
```

This works fine for direct query usage, but when defining the parameter to be optional then enum information is gone from the generated OpenAPI definition.

Behavior is reproduced in the repo by adding an additionall test in `VerifyYamlTest.scala` where `Validation.in_enum_class` is modified to be wrapped in Option.

I have tried to look for a fix and have added `Validator.CollectionElements` in `asPrimitiveValidators` for `openapi-docs` but currently stuck with `EncodeToAny` in `addConstraints`. Can open a PR if it would be helpful?

Might this also be related to the issues mpapillon is having in #224?

**Comment by mpapillon** [comment]
Yes, it is related to the issue #224. I have the same problem with `addConstraints`, but I didn't have time to suggest a PR.

**Comment by adamw** [comment]
Should be fixed in 0.11.4 - please check :)

**Comment by perok** [comment]
This did indeed fix the issue for optional query parameters 🎉 Thanks @freekh! But enums in the schema definition as per issue #224 was not resolved.

**Comment by adamw** [comment]
@perok hmm ... isn't it the scenario as in this test: https://github.com/softwaremill/tapir/commit/39bb47e4769519fc4b3e9a4b66c49af6469870a7 ?

**Comment by perok** [comment]
Oh sorry, I was refeering to the schema references which uses the component section. 39bb47e test is about parameter schemas and that part works now.

By using the same code as described above with the example in #224 I only get `type: string`. I might have time to look further into the issue next week :)

**Comment by adamw** [comment]
@perok hm ... not sure I understand, but can you maybe create a simple example with expected yaml output, so that I can debug and see what's wrong? :)

**Comment by adamw** [comment]
(probably in a new issue)

**Comment by ranglang** [comment]
same error

**Comment by adamw** [comment]
@ranglang what error and produced by what code? :)
